/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author ayseserra
 */
public class ExportFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExportFrame
     */
    public ExportFrame() {
        initComponents();
    }
    private boolean exportUsers = false;
    private boolean exportMaterials = false;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_export = new javax.swing.JButton();
        jCheckBox_user = new javax.swing.JCheckBox();
        jCheckBox_mtrl = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btn_export.setBackground(new java.awt.Color(153, 0, 153));
        btn_export.setForeground(new java.awt.Color(255, 255, 255));
        btn_export.setText("Export");
        btn_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportActionPerformed(evt);
            }
        });

        jCheckBox_user.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox_user.setText("Users");
        jCheckBox_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_userActionPerformed(evt);
            }
        });

        jCheckBox_mtrl.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox_mtrl.setText("Materials");
        jCheckBox_mtrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_mtrlActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Please select the field(s) whose information you want to print to the file.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox_user)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_mtrl))
                    .addComponent(btn_export)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_user)
                    .addComponent(jCheckBox_mtrl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_export)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportActionPerformed
       //The export button will list all materials and users in the frame and write them to the file.
        
        StringBuilder exportData = new StringBuilder();

        if (exportUsers) {
            ResultSet usersResultSet = Database.SelectUsers(null);
            try {
                while (usersResultSet.next()) {
                    exportData.append("ID: ").append(usersResultSet.getInt("id")).append(", ")
                            .append("Username: ").append(usersResultSet.getString("username")).append(", ")
                            .append("Password: ").append(usersResultSet.getString("password")).append(", ")
                            .append("User Type: ").append(usersResultSet.getInt("user_type")).append("\n");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

        if (exportMaterials) {
            ResultSet materialsResultSet = Database.SelectMaterials(null);
            try {
                while (materialsResultSet.next()) {
                    exportData.append("Material ID: ").append(materialsResultSet.getInt("materialId")).append(", ")
                            .append("Material Name: ").append(materialsResultSet.getString("material_name")).append(", ")
                            .append("Quantity: ").append(materialsResultSet.getInt("quantity")).append(", ")
                            .append("Category: ").append(materialsResultSet.getString("category")).append("\n");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

        jTextArea1.setText(exportData.toString());

        // write to file
        String fileName = "C:\\Users\\EMRULLAH\\Documents\\NetBeansProjects\\project\\exported_data.txt";

        try ( BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            writer.write(exportData.toString());
            System.out.println("Exported data to file: " + fileName);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btn_exportActionPerformed

    private void jCheckBox_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_userActionPerformed
        exportUsers = jCheckBox_user.isSelected();
    }//GEN-LAST:event_jCheckBox_userActionPerformed

    private void jCheckBox_mtrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_mtrlActionPerformed
        exportMaterials = jCheckBox_mtrl.isSelected();
    }//GEN-LAST:event_jCheckBox_mtrlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_export;
    private javax.swing.JCheckBox jCheckBox_mtrl;
    private javax.swing.JCheckBox jCheckBox_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
